version: '3'
services:
  ptushki-postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'username'
      POSTGRES_DB: 'ptushki'
    ports:
      - '${PG_PORT}:5432'
  ptushki-postgres-test:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'username'
      POSTGRES_DB: 'ptushki-test'
    ports:
      - '${PG_TEST_PORT}:5432'
